# Generated by Django 3.1 on 2021-06-10 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts_fields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_zoho_ref', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Field Zoho Ref')),
                ('field_api_name', models.CharField(max_length=50, verbose_name='API Name')),
                ('field_label', models.CharField(max_length=50, verbose_name='Label')),
                ('field_type', models.CharField(editable=False, max_length=50, verbose_name='Type')),
                ('field_layout_permissions', models.CharField(editable=False, max_length=50, verbose_name='Layout Permissions')),
                ('field_size', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Field Size')),
                ('field_iscustom', models.BooleanField(blank=True, db_index=True, editable=False, null=True, verbose_name='Is Custom Field')),
                ('field_ismandatory', models.BooleanField(blank=True, db_index=True, editable=False, null=True, verbose_name='Is Mandatory')),
                ('field_isreadonly', models.BooleanField(blank=True, db_index=True, editable=False, null=True, verbose_name='Is Read Only')),
                ('field_isformulafield', models.BooleanField(blank=True, editable=False, null=True, verbose_name='Is Formula Field')),
                ('field_iscurrencyfield', models.BooleanField(blank=True, editable=False, null=True, verbose_name='Is Currency Field')),
                ('field_data', models.JSONField(blank=True, null=True, verbose_name='Default Data')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='contacts_browse_layout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_col', models.IntegerField(verbose_name='Column Number')),
                ('layout_col_width', models.IntegerField(verbose_name='Column Width')),
                ('layout_field_searchable', models.BooleanField(db_index=True, verbose_name='Column Searchable')),
                ('layout_field_sortable', models.BooleanField(db_index=True, verbose_name='Column Sortable')),
                ('layout_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacts_fields')),
            ],
            options={
                'verbose_name': 'Browse Contacts Layout',
                'verbose_name_plural': 'Browse Contacts Layout',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='contacts_addedit_layout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_row', models.IntegerField(verbose_name='Row Number')),
                ('layout_col', models.IntegerField(verbose_name='Column Number')),
                ('layout_col_size', models.IntegerField(help_text='Total grid size for a full row should be 12', verbose_name='Column Grid Size')),
                ('layout_field_display_add_screen', models.BooleanField(db_index=True, default=False, verbose_name="Show on 'Add' screen")),
                ('layout_field_display_only', models.BooleanField(db_index=True, default=False, verbose_name='Column Data NOT editable')),
                ('layout_nbsp', models.BooleanField(db_index=True, default=False, verbose_name='Column is a whitespace')),
                ('layout_hr', models.BooleanField(db_index=True, default=False, verbose_name='Section separator')),
                ('layout_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contacts_fields')),
            ],
            options={
                'verbose_name': 'Add/Edit Contact Layout',
                'verbose_name_plural': 'Add/Edit Contact Layout',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoho_ref', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Last Updated')),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
