# Generated by Django 3.1 on 2021-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210524_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unread',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
