# Generated by Django 3.1 on 2021-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210524_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.TextField(default='off'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.IntegerField(),
        ),
    ]
