# Generated by Django 3.1 on 2021-05-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0006_groupmessagepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagepermission',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessagepermission',
            name='receiver_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='groupmessagepermission',
            name='sender_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.group'),
        ),
    ]
