# Generated by Django 3.1 on 2021-05-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210525_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessagepermission',
            name='enable',
        ),
        migrations.AddField(
            model_name='groupmessagepermission',
            name='enabled',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Can Send Messages?'),
        ),
    ]
