# Generated by Django 3.1 on 2021-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210525_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessagepermission',
            name='enabled',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Can Send Messages?'),
        ),
    ]
